name: 'GNU Arm Embedded Toolchain'
description: 'Install arm-none-eabi-gcc'
author: 'Ryan Winter'
inputs:
  release:
    description: 'GNU Arm Embedded Toolchain release name, in the V-YYYY-qZ format (e.g. "9-2019-q4")'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'green'
